// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCatQI0ovZYnR0EnQa4-7KcSoAMvpTYB4M',
    appId: '1:156708132240:android:3a986e604e6273af154f15',
    messagingSenderId: '156708132240',
    projectId: 'word-learn-18813',
    storageBucket: 'word-learn-18813.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrLvVMIBAfRzxX1n5Z3iEIHHHDrEdpaB0',
    appId: '1:156708132240:ios:ed8c42e2856fe928154f15',
    messagingSenderId: '156708132240',
    projectId: 'word-learn-18813',
    storageBucket: 'word-learn-18813.appspot.com',
    iosClientId: '156708132240-76p3ljignff899haka331j5mio8ptmn2.apps.googleusercontent.com',
    iosBundleId: 'com.zsoltkebel.wordLearn',
  );
}
